### ISSUE TITLE
Operating at Daylight Savings during Standard Time

### ISSUE THREAD

**Issue by khader137** [tazzix/SalahWear#8]
The Salah time calculation methods cover just about every option, it does not require a separate app on the phone, and it simply looks amazing! I can't wait to use Salah Wear...

...only issue is that the app shows all 5 daily Salah times at Daylight Saving time zone while it is Standard Time in USA now. I've tried different settings but it wouldn't correct itself. I'm not sure how to troubleshoot this.

Is there something I'm missing or doing wrong? Hoping to learn for a way to fix this.

**Comment by tazzix** [comment]
Please try the latest version and let me know if you are still facing the issue.

**Comment by khader137** [comment]
Hi, thank you so much! Love the +1 / 0 / -1 solution implemented for daylight saving changes.
The two complication options are also amazing ...all of this just in time for Ramadan!!

Thanks again for the latest version @tazzix , _barek Allahu feek_

**Comment by tazzix** [comment]
So happy to know it solved your problem, and a big shout out for the developers who sent PRs for both of these features. @grimpy and @OJ7
